//
//  UIColor+Additions.swift
//  MyJoi
//
//  Created by Nerneen Mohamed on 11/27/18.
//  Copyright © 2018 Nermeen Mohamed. All rights reserved.
////  Generated by Zeplin on 11/27/17.


import UIKit
extension UIColor {
    
    @nonobjc class var vieSteel: UIColor {
        return UIColor(red: 117.0 / 255.0, green: 134.0 / 255.0, blue: 146.0 / 255.0, alpha: 1.0)
    }
}
